.Step 1

Understand the system under test a.k.a SUT. +

----
+ - - - - - - - - - - - - - - - - - - - - - - - - - - - +
' SUT:                                                  '
'                                                       '
' +-------------------+  converter   +----------------+ '  send cmd   +----------------+
' | ResourceAssembler | <----------- | RestController | ' ----------> | CommandHandler |
' +-------------------+              +----------------+ '             +----------------+
'                                                       '
+ - - - - - - - - - - - - - - - - - - - - - - - - - - - +
                                       |
                                       | query
                                       v
                                     +----------------+
                                     |   Repository   |
                                     +----------------+
----

1) Why mock `Repository` and `CommandHandler`? +
2) Why not mock `ResourceAssembler`? +
3) Why not test with `CatalogRestController.all()`? +
4) Why slice test with `@WebMvcTest`? +

.Step 2

Understand @WebMvcTest. +

1) Understand `MockMvc` +
2) Understand `MockMvcRequestBuilders.get()`. How to issue a `POST` request? +
3) Understand `andExpect()` and `MockMvcResultMatchers.get()`.  +
4) Understand `andExpect()` and `MockMvcResultMatchers.jsonPath()`.  +
5) Understand `andDo()` and `MockMvcResultHandlers.log()`.  +
6) Understand `MockMvcBuilderCustomizer`.  +
7) Assert `_embedded.catalogs` has two items. +
8) Assert `_embedded.catalogs[].price` is present. +
9) Assert `_links.self` is present. +

.Step 3

Understand API Contract. +

1) Why doc? +
2) Why not `Swagger`? +
3) Understand `MockMvcRestDocumentation.document()` +
4) Understand `PayloadDocumentation.responseFields()` +
5) Doc `status`
6) Understand `HypermediaDocumentation.halLinks()` +
7) Understand generated snippets +
8) Understand `RequestDocumentation`, what about find orders by status +
9) Understand `ResponseFieldsSnippet.andWithPrefix()` +
10) Why `Spring REST Docs`? +

.Step 4

Understand API stubbing. +

1) Understand `spring-cloud-contract-wiremock`? +
2) Understand `WireMockRestDocs.verify()` +
3) Understand `withHeader()`/`withBody()` +
4) Why stubbing? +
5) How to publish stubs? +

.Step 5

Understand the test hierarchy. +

1) Understand `OrderResource.totalAmount` +
2) Is it an overkill to test the `OrderResource.totalAmount` by `@WebMvcTest`  +
3) Understand test suite
4) Understand `@SpringBootTest`

.Step 6

Cleanup. +

1) Understand `Test Fixture` +
2) Try to introduce `OrderFixture` and cleanup `Order` setup in all tests.
3) Try to eliminate duplicates for API contract verifications.
